### ISSUE TITLE
Error when ingesting resources.

### ISSUE THREAD

**Issue by xino12** [cloudquery/cq-provider-gcp#11]
in some of our projects we see that there's a NPE when ingesting some resources. It only fails for some GCP projects, for others it works properly.

```
3:23PM DBG panic: runtime error: invalid memory address or nil pointer dereference
3:23PM DBG [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x107d86a]
3:23PM DBG 
3:23PM DBG goroutine 60 [running]:
3:23PM DBG github.com/cloudquery/cq-provider-gcp/resources/compute.(*Client).transformInstance(0xc0009c3cc0, 0xc0000c9180, 0x8)
3:23PM DBG 	/home/ruben/workspace/cq-provider-gcp/resources/compute/instances.go:541 +0x8aa
3:23PM DBG github.com/cloudquery/cq-provider-gcp/resources/compute.(*Client).transformInstances(0xc0009c3cc0, 0xc0001dafc0, 0xb, 0xd, 0x0, 0x0, 0x0)
3:23PM DBG 	/home/ruben/workspace/cq-provider-gcp/resources/compute/instances.go:550 +0x7e
3:23PM DBG github.com/cloudquery/cq-provider-gcp/resources/compute.(*Client).instances(0xc0009c3cc0, 0x141de60, 0x0, 0x1, 0x3)
3:23PM DBG 	/home/ruben/workspace/cq-provider-gcp/resources/compute/instances.go:593 +0x18b
3:23PM DBG github.com/cloudquery/cq-provider-gcp/resources/compute.(*Client).CollectResource(0xc0009c3cc0, 0xc000636278, 0x9, 0x141de60, 0x0, 0x1, 0xc000262080)
3:23PM DBG 	/home/ruben/workspace/cq-provider-gcp/resources/compute/client.go:41 +0x227
3:23PM DBG github.com/cloudquery/cq-provider-gcp/provider.(*Provider).collectResource(0xc00010e300, 0xc0009a8a50, 0xd, 0xc000636270, 0x11, 0x141de60, 0x0, 0x0, 0x0)
3:23PM DBG 	/home/ruben/workspace/cq-provider-gcp/provider/provider.go:189 +0x157
3:23PM DBG github.com/cloudquery/cq-provider-gcp/provider.(*Provider).Fetch.func1(0x0, 0x0)
3:23PM DBG 	/home/ruben/workspace/cq-provider-gcp/provider/provider.go:154 +0x66
3:23PM DBG golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000594600, 0xc000594720)
3:23PM DBG 	/home/ruben/go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57 +0x59
3:23PM DBG created by golang.org/x/sync/errgroup.(*Group).Go
3:23PM DBG 	/home/ruben/go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:54 +0x66
Error: rpc error: code = Unavailable desc = transport is closing
3:23PM DBG plugin process exited error="exit status 2" path=/home/ruben/workspace/cloudquery/.cq/providers/cloudquery/gcp/latest-linux-amd64 pid=1703376
3:23PM DBG received EOF, stopping recv loop err="rpc error: code = Unavailable desc = transport is closing"

```

Thanks

**Comment by yevgenypats** [comment]
Should be fixed with https://github.com/cloudquery/cq-provider-gcp/releases/tag/v0.0.12
